package com.myspace.proj1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("EO Number")
	private java.lang.Integer eo;
	@org.kie.api.definition.type.Label("EO Payload")
	private java.lang.String payload;
	@org.kie.api.definition.type.Label("Status of EO")
	private java.util.List<java.lang.String> status;

	@org.kie.api.definition.type.Label("field 1")
	private java.util.Date f1;

	@org.kie.api.definition.type.Label(value = "F2 field")
	private java.lang.Byte f2;

	public testDO() {
	}

	public java.lang.Integer getEo() {
		return this.eo;
	}

	public void setEo(java.lang.Integer eo) {
		this.eo = eo;
	}

	public java.lang.String getPayload() {
		return this.payload;
	}

	public void setPayload(java.lang.String payload) {
		this.payload = payload;
	}

	public java.util.List<java.lang.String> getStatus() {
		return this.status;
	}

	public void setStatus(java.util.List<java.lang.String> status) {
		this.status = status;
	}

	public java.util.Date getF1() {
		return this.f1;
	}

	public void setF1(java.util.Date f1) {
		this.f1 = f1;
	}

	public java.lang.Byte getF2() {
		return this.f2;
	}

	public void setF2(java.lang.Byte f2) {
		this.f2 = f2;
	}

	public testDO(java.lang.Integer eo, java.lang.String payload,
			java.util.List<java.lang.String> status, java.util.Date f1,
			java.lang.Byte f2) {
		this.eo = eo;
		this.payload = payload;
		this.status = status;
		this.f1 = f1;
		this.f2 = f2;
	}

}